# Generated by Django 2.0.7 on 2018-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='startup',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
