# Generated by Django 2.0.7 on 2018-08-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180810_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='startup_overview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
